#! /bin/sh
#**************************************************************************
#  Copyright International Business Machines Corp, 2018. 
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#**************************************************************************

convert()
{
 # echo "Converting $1"
  RESULT_FILE=$1.graph

  echo "Time Ux Uy Epsilon P K" 

  awk 'BEGIN{
        time=0;
        Ux=0; 
        Uy=0;
        epsilon=0;
        pValue=0;
        kValue=0;
        fmt="%d %f %f %f %f %f\n";
    }{
       #found a new section start with Time = 
       if ($1 == "Time" && $2 == "=" ){
           if(time != 0 ){
           # this is not the first line, print out previous line
                if(Ux > 0){
                    printf(fmt, time, Ux, Uy, epsilon,pValue, kValue); 
                }
                Ux=0;
                Uy=0;
                epsilon=0;
                pValue=0;
                kValue=0;
           }
           time=$3;
       } else if ($2 == "Solving" && $3 == "for") {
               if($4 == "Ux,") { 
                   Ux = $8 + 0;
               }else if ($4 == "Uy,"){
                   Uy = $8 + 0;
               }else if ($4 == "epsilon,"){
                   epsilon = $8 + 0;
               }else if ($4 == "p,"){
                   pValue = $8 + 0;
               }else if ($4 == "k,"){
                   kValue = $8 + 0;
               }

       }
    } END {
       if(Ux > 0){
           printf(fmt, time, Ux, Uy, epsilon,pValue, kValue);
       }
    }' $1  #>> $RESULT_FILE


}

if [ "x$1" = "x"  ]; then
   echo "Need to specify  a file."
   exit
fi
if [ ! -f $1 ]; then
   echo "Need to specify a valid file."
   exit
fi
#if [ -f system/decomposeParDict ];then
#  echo "convertData: Processing parallel openfoam result."
#fi
convert  $1 
