#!/bin/bash
#**************************************************************************
#  Copyright International Business Machines Corp, 2018. 
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#**************************************************************************
PVLOG=/tmp/pvlog.$USER.$$
echo $0, $1 >> $PVLOG 
id >> $PVLOG
echo "DISPLAY $DISPLAY" >> $PVLOG

export LANG=C
export LC_ALL=C

if [ "x$1" = "x" ];then
   #start application without input data
   export CDIR=$HOME
   DATA_OPTION=""
else
   #take the input data file
   DATA_FILE=$1

   #get the job working directory passed from the $DATA_FILE
   FF=`basename $DATA_FILE`
   #export CDIR=`echo $DATA_FILE |sed s/$FF//g`
   export CDIR=`dirname $DATA_FILE`
   DATA_OPTION="--data=$FF"
fi

PARAVIEW_CMD=paraview

BSUB_SCRIPT=$CDIR/bsub.paraview
exec 3>&1  # Link file descriptor #3 with stdout.
exec > $BSUB_SCRIPT  # stdout replaced with file "bsub.$JOBNAME".
echo "#!/bin/bash"
echo
echo "if [ -f /opt/openfoam6/etc/bashrc ]; then"
echo "   source /opt/openfoam6/etc/bashrc"
echo "elif [ -f /opt/OpenFOAM-v1912/etc/bashrc ]; then"
echo "   source /opt/OpenFOAM-v1912/etc/bashrc"
echo "fi"
echo
echo "$PARAVIEW_CMD $DATA_OPTION"

exec 1>&3 3>&-  # Restore stdout and close file descriptor #3.

chmod a+x $BSUB_SCRIPT

JOB_NAME="ParaView"

echo bsub -app openfoam -R "defined(ParaView)" -env DISPLAY=$DISPLAY -J $JOB_NAME -K -o paraview_output%J.txt -cwd $CDIR $BSUB_SCRIPT >> $PVLOG

     bsub -app openfoam -R "defined(ParaView)" -env DISPLAY=$DISPLAY -J $JOB_NAME -K -o paraview_output%J.txt -cwd $CDIR $BSUB_SCRIPT
     
