#!/bin/bash
#**************************************************************************
#  Copyright International Business Machines Corp, 2018. 
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#**************************************************************************
PVLOG=/tmp/pvlog.$$
echo $0, $1 >> $PVLOG 
id >> $PVLOG
echo "DISPLAY $DISPLAY" >> $PVLOG

export LANG=C
export LC_ALL=C

if [ "x$1" = "x" ];then
   #start application without input data
   export CDIR=/home/$USER/paraview 
   mkdir -p $CDIR
   DATA_OPTION=""
else
   #take the input data file
   DATA_FILE=$1

   #get the job working directory passed from the $DATA_FILE
   FF=`basename $DATA_FILE`
   #export CDIR=`echo $DATA_FILE |sed s/$FF//g`
   export CDIR=`dirname $DATA_FILE`
   DATA_OPTION="--data=$FF"
fi

PARAVIEW_CMD=paraview

PARAVIEW_SCRIPT=$CDIR/paraview.script
exec 3>&1  # Link file descriptor #3 with stdout.
exec > $PARAVIEW_SCRIPT  # stdout replaced with file "bsub.$JOBNAME".
echo "#!/bin/bash"
echo
echo "source /opt/openfoam6/etc/bashrc"
echo
echo "$PARAVIEW_CMD $DATA_OPTION"

exec 1>&3 3>&-  # Restore stdout and close file descriptor #3.

chmod a+x $PARAVIEW_SCRIPT

cd $CDIR
#assume dockerpasswd.sh is in the same directory with current script.
CMD_PATH=`dirname $0`
export LS_EXECCWD=$CDIR
export LSB_JOBID=$$
PASSWD_MAP=`$CMD_PATH/dockerPasswd.sh` 

if [ "x${job_repo}" != "x" ];then
  JOB_REPO_MAP=" -v ${job_repo}:${job_repo} "
else
  JOB_REPO_MAP=""
fi

export USER_ID=$(id -u)
export GROUP_ID=$(id -g)


echo /bin/docker run --rm --entrypoint=   -e DISPLAY=$DISPLAY -e HOME=/home/$USER -w=/home/$USER -u $USER_ID:$GROUP_ID --net=host --ipc=host $PASSWD_MAP -v $CDIR:/home/$USER $JOB_REPO_MAP openfoam/openfoam6-paraview54 /home/$USER/paraview.script  >> $PVLOG

/bin/docker run --rm --entrypoint=   -e DISPLAY=$DISPLAY -e HOME=/home/$USER -w=/home/$USER -u $USER_ID:$GROUP_ID --net=host --ipc=host $PASSWD_MAP -v $CDIR:/home/$USER $JOB_REPO_MAP openfoam/openfoam6-paraview54 /home/$USER/paraview.script  

